apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: pbl-
configMapGenerator:
  - name: serviceNames
    literals:
      - PROD=true
      - REDIS_URL=redis-master
      - MONGODB_URL=mongodb

generatorOptions:
  disableNameSuffixHash: true
